// Generated by scripts/media.mjs — do not edit by hand. Run `npm run media`.

export interface MediaAsset {
  width: number
  height: number
  avif: string
  webp: string
  src: string
  placeholder: string
}

export const media = {
  'engine-editor': {
    width: 1600,
    height: 909,
    avif: 'media/engine-editor-800.avif 800w, media/engine-editor-1200.avif 1200w, media/engine-editor-1600.avif 1600w',
    webp: 'media/engine-editor-800.webp 800w, media/engine-editor-1200.webp 1200w, media/engine-editor-1600.webp 1600w',
    src: 'media/engine-editor-1200.webp',
    placeholder: 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAwCdASoYAA4APu1iqk4ppaQiMAgBMB2JZwDDNCHf45ipu3bgAAD+6R1zI4fmBibO4M6IXKeq6QnZ/YAAAA==',
  },
  'engine-table': {
    width: 1600,
    height: 824,
    avif: 'media/engine-table-800.avif 800w, media/engine-table-1200.avif 1200w, media/engine-table-1600.avif 1600w',
    webp: 'media/engine-table-800.webp 800w, media/engine-table-1200.webp 1200w, media/engine-table-1600.webp 1600w',
    src: 'media/engine-table-1200.webp',
    placeholder: 'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoYAAwALrV2u12jqampiYC0SygABchwa+ZJhjOc8GiUAAD++cGMe77o92RIiEjpP+014zEhMh+oIfy92J6sk6KtMhAAAA==',
  },
  'engine-hand': {
    width: 1600,
    height: 824,
    avif: 'media/engine-hand-800.avif 800w, media/engine-hand-1200.avif 1200w, media/engine-hand-1600.avif 1600w',
    webp: 'media/engine-hand-800.webp 800w, media/engine-hand-1200.webp 1200w, media/engine-hand-1600.webp 1600w',
    src: 'media/engine-hand-1200.webp',
    placeholder: 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAwCdASoYAAwAPu1yrU+pp6QiMAgBMB2JaQAAW+y1V4uM0OHcAAD+9COwiUfRNNVs0+4uCjbIAAAA',
  },
  'engine-judging': {
    width: 1600,
    height: 824,
    avif: 'media/engine-judging-800.avif 800w, media/engine-judging-1200.avif 1200w, media/engine-judging-1600.avif 1600w',
    webp: 'media/engine-judging-800.webp 800w, media/engine-judging-1200.webp 1200w, media/engine-judging-1600.webp 1600w',
    src: 'media/engine-judging-1200.webp',
    placeholder: 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoYAAwAPu1mqk2ppaQiMAgBMB2JZwAAW+sbK/N79RAA/vQjugAvJtSLLwrFqkWL4C/hW24oAAA=',
  },
  'engine-skyward': {
    width: 1600,
    height: 824,
    avif: 'media/engine-skyward-640.avif 640w, media/engine-skyward-1024.avif 1024w, media/engine-skyward-1600.avif 1600w',
    webp: 'media/engine-skyward-640.webp 640w, media/engine-skyward-1024.webp 1024w, media/engine-skyward-1600.webp 1600w',
    src: 'media/engine-skyward-1024.webp',
    placeholder: 'data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoYAAwAPu1iqU2ppaOiMAgBMB2JaACdMoR3ABZ41sGN39AA/ozDD9RjxiE7vtJbXjzq+RK2LTmuFvpc8QABLTfAlFU4PMhKU3S4AA==',
  },
  'cards-tv-lobby': {
    width: 3200,
    height: 1800,
    avif: 'media/cards-tv-lobby-800.avif 800w, media/cards-tv-lobby-1280.avif 1280w, media/cards-tv-lobby-1920.avif 1920w, media/cards-tv-lobby-2560.avif 2560w',
    webp: 'media/cards-tv-lobby-800.webp 800w, media/cards-tv-lobby-1280.webp 1280w, media/cards-tv-lobby-1920.webp 1920w, media/cards-tv-lobby-2560.webp 2560w',
    src: 'media/cards-tv-lobby-1280.webp',
    placeholder: 'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoYAA0APu1yrU+pp6QiMAgBMB2JaQAAW14SAIImHAAA/vQipqY3q9ClZUbvLTFiSXx3fiMdyUsw+j11yreH1qqQWAAAAA==',
  },
  'cards-tv-reveal': {
    width: 3200,
    height: 1800,
    avif: 'media/cards-tv-reveal-800.avif 800w, media/cards-tv-reveal-1280.avif 1280w, media/cards-tv-reveal-1920.avif 1920w, media/cards-tv-reveal-2560.avif 2560w',
    webp: 'media/cards-tv-reveal-800.webp 800w, media/cards-tv-reveal-1280.webp 1280w, media/cards-tv-reveal-1920.webp 1920w, media/cards-tv-reveal-2560.webp 2560w',
    src: 'media/cards-tv-reveal-1280.webp',
    placeholder: 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAwCdASoYAA0ALrV2u12jqampiYC0S0gABc6kSw5IkwAAAP724sGN9lhPpCZP70xEPYblQlWsqZwwfX3eeAAA',
  },
  'cards-tv-winner': {
    width: 3200,
    height: 1800,
    avif: 'media/cards-tv-winner-800.avif 800w, media/cards-tv-winner-1280.avif 1280w, media/cards-tv-winner-1920.avif 1920w',
    webp: 'media/cards-tv-winner-800.webp 800w, media/cards-tv-winner-1280.webp 1280w, media/cards-tv-winner-1920.webp 1920w',
    src: 'media/cards-tv-winner-1280.webp',
    placeholder: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAABwAwCdASoYAA0APu1kqk4ppaQiMAgBMB2JaQAAW+tBB9q0fiAA/vQcf8Wmus35bapoH7swAAA=',
  },
  'cards-phone-judge': {
    width: 1170,
    height: 2532,
    avif: 'media/cards-phone-judge-390.avif 390w, media/cards-phone-judge-780.avif 780w, media/cards-phone-judge-1170.avif 1170w',
    webp: 'media/cards-phone-judge-390.webp 390w, media/cards-phone-judge-780.webp 780w, media/cards-phone-judge-1170.webp 1170w',
    src: 'media/cards-phone-judge-780.webp',
    placeholder: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBQCdASoYADQAPu1or06ppiSiLAmZMB2JaQAAPqFRN7LtmjXiVmv0dz2/4MKowKL0VjAA/u6xYx6yM+mfyhi3Yn7e8VcnSgC2w6+0X/G2ROCCEOkvx8+wpLvqgTk3Da7zYPKVIFOfpz4arA3jdgd4+d66LqZeMKmVxqdSAAA=',
  },
  'voxel-sunset': {
    width: 1280,
    height: 720,
    avif: 'media/voxel-sunset-640.avif 640w, media/voxel-sunset-1280.avif 1280w',
    webp: 'media/voxel-sunset-640.webp 640w, media/voxel-sunset-1280.webp 1280w',
    src: 'media/voxel-sunset-1280.webp',
    placeholder: 'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoYAA4APu1kqk2ppaQiMAgBMB2JQBOgA83b3QpukolU5bQAzeBpCE5UWEHDpEvFVpB/wNhZEUuPIuQWTkgh9lIvMCb8xfo8THZtE6Q2ZeAAAA==',
  },
  'voxel-gameplay': {
    width: 1280,
    height: 720,
    avif: 'media/voxel-gameplay-640.avif 640w, media/voxel-gameplay-1280.avif 1280w',
    webp: 'media/voxel-gameplay-640.webp 640w, media/voxel-gameplay-1280.webp 1280w',
    src: 'media/voxel-gameplay-1280.webp',
    placeholder: 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQBACdASoYAA4APu1qrU8ppiQiMAgBMB2JYwCdAB6uLXuJKHtquMCeAAD82OkesHPweMzjrGlh9aCmmB/LHD6DE/e3MJiffYp/PYZZQ/fQxKIAAAA=',
  },
  'sunburn-poster': {
    width: 1348,
    height: 1907,
    avif: 'media/sunburn-poster-600.avif 600w, media/sunburn-poster-1000.avif 1000w, media/sunburn-poster-1348.avif 1348w',
    webp: 'media/sunburn-poster-600.webp 600w, media/sunburn-poster-1000.webp 1000w, media/sunburn-poster-1348.webp 1348w',
    src: 'media/sunburn-poster-1000.webp',
    placeholder: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwBQCdASoYACIAPt1YpU2opSeiNVv8ARAbiWUAyywhX9+/etbSWrNiry6zXm5v8+XsUyYwAP7tQPDa8F5Qj2eWWyiIXFC2q6XiZFdN+r1CVw5GoAjHKwatZs84LM0MpHrtjh1bfEVtx9Gu8hkmr/avV4zUCzMEAAA=',
  },
  'sunburn-wiring': {
    width: 2400,
    height: 1800,
    avif: 'media/sunburn-wiring-800.avif 800w, media/sunburn-wiring-1600.avif 1600w',
    webp: 'media/sunburn-wiring-800.webp 800w, media/sunburn-wiring-1600.webp 1600w',
    src: 'media/sunburn-wiring-1600.webp',
    placeholder: 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAwCdASoYABIAPu1iqU2ppaQiMAgBMB2JZwAAXBnvaDq3gVDiiyYAAP7wB2iFxb+VN2tcoXyD5QBp3osyCqNr4/27MYAA',
  },
  'neurogrip-watch': {
    width: 1260,
    height: 1260,
    avif: 'media/neurogrip-watch-420.avif 420w, media/neurogrip-watch-840.avif 840w, media/neurogrip-watch-1260.avif 1260w',
    webp: 'media/neurogrip-watch-420.webp 420w, media/neurogrip-watch-840.webp 840w, media/neurogrip-watch-1260.webp 1260w',
    src: 'media/neurogrip-watch-840.webp',
    placeholder: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAABwAwCdASoYABgAPu1srFEppiQiqAqpMB2JZwDE2A9qiMlBpeAA/uPmlkRwYi0dk0XzF060eZwoksM2VHixNv5ajAAAAA==',
  },
} as const satisfies Record<string, MediaAsset>

export type MediaId = keyof typeof media
