// Builds the site's images from media-src/ into public/media/ and writes a
// typed manifest (src/content/media.gen.ts) with intrinsic sizes, srcsets and
// a tiny blurred placeholder for each image.
//
// To add an image: drop the original into media-src/, add a line to IMAGES,
// run `npm run media`, then reference it by id from src/content/projects.ts.

import sharp from 'sharp'
import { mkdir, writeFile, rm } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'media-src')
const OUT = join(ROOT, 'public', 'media')
const MANIFEST = join(ROOT, 'src', 'content', 'media.gen.ts')

/** ui: interface screenshots keep crisp text, so they get a higher quality. */
const IMAGES = [
  { id: 'engine-editor', file: 'engine-editor.png', widths: [800, 1200, 1600], ui: true },
  { id: 'engine-table', file: 'engine-table.jpg', widths: [800, 1200, 1600] },
  { id: 'engine-hand', file: 'engine-hand.jpg', widths: [800, 1200, 1600] },
  { id: 'engine-judging', file: 'engine-judging.jpg', widths: [800, 1200, 1600] },
  { id: 'engine-skyward', file: 'engine-skyward.jpg', widths: [640, 1024, 1600] },
  { id: 'cards-tv-lobby', file: 'cards-tv-lobby.png', widths: [800, 1280, 1920, 2560], ui: true },
  { id: 'cards-tv-reveal', file: 'cards-tv-reveal.png', widths: [800, 1280, 1920, 2560], ui: true },
  { id: 'cards-tv-winner', file: 'cards-tv-winner.png', widths: [800, 1280, 1920], ui: true },
  { id: 'cards-phone-judge', file: 'cards-phone-judge.png', widths: [390, 780, 1170], ui: true },
  { id: 'voxel-sunset', file: 'voxel-sunset.png', widths: [640, 1280] },
  { id: 'voxel-gameplay', file: 'voxel-gameplay.png', widths: [640, 1280] },
  { id: 'sunburn-poster', file: 'sunburn-poster.png', widths: [600, 1000, 1348], ui: true },
  { id: 'sunburn-wiring', file: 'sunburn-wiring.png', widths: [800, 1600], ui: true },
  { id: 'neurogrip-watch', file: 'neurogrip-watch.png', widths: [420, 840, 1260], ui: true },
]

await rm(OUT, { recursive: true, force: true })
await mkdir(OUT, { recursive: true })

const entries = []
for (const image of IMAGES) {
  const input = join(SRC, image.file)
  const { width, height } = await sharp(input).metadata()
  const widths = [...new Set(image.widths.map((w) => Math.min(w, width)))]
  const avif = []
  const webp = []

  for (const w of widths) {
    const base = sharp(input).resize({ width: w, withoutEnlargement: true })
    const name = `${image.id}-${w}`
    await base
      .clone()
      .avif({ quality: image.ui ? 62 : 52, effort: 6 })
      .toFile(join(OUT, `${name}.avif`))
    await base
      .clone()
      .webp({ quality: image.ui ? 86 : 78, effort: 6 })
      .toFile(join(OUT, `${name}.webp`))
    avif.push(`media/${name}.avif ${w}w`)
    webp.push(`media/${name}.webp ${w}w`)
  }

  const tiny = await sharp(input).resize({ width: 24 }).blur(1.2).webp({ quality: 40 }).toBuffer()
  const mid = widths[Math.min(1, widths.length - 1)]
  entries.push({
    id: image.id,
    width,
    height,
    avif: avif.join(', '),
    webp: webp.join(', '),
    src: `media/${image.id}-${mid}.webp`,
    placeholder: `data:image/webp;base64,${tiny.toString('base64')}`,
  })
  console.log(`${image.id.padEnd(20)} ${width}x${height} -> ${widths.join(', ')}`)
}

const body = entries
  .map(
    (e) => `  '${e.id}': {
    width: ${e.width},
    height: ${e.height},
    avif: '${e.avif}',
    webp: '${e.webp}',
    src: '${e.src}',
    placeholder: '${e.placeholder}',
  },`,
  )
  .join('\n')

await writeFile(
  MANIFEST,
  `// Generated by scripts/media.mjs — do not edit by hand. Run \`npm run media\`.

export interface MediaAsset {
  width: number
  height: number
  avif: string
  webp: string
  src: string
  placeholder: string
}

export const media = {
${body}
} as const satisfies Record<string, MediaAsset>

export type MediaId = keyof typeof media
`,
)
console.log(`wrote ${entries.length} entries -> src/content/media.gen.ts`)
